server:
  port: 8082
spring:
  application:
    name: consumer-api
    version: "@project.version@"

app:
  customer:
    url: "http://localhost:8081/api/v1"
  person:
    url: "http://localhost:8083"